version: '3.8'

services:
  web:
    build: .
    container_name: srmartinez_web
    restart: always
    # ports:
    #  - "80:80" (Removido para que Dokploy se encargue del enrutamiento)
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=srmartinez.site,www.srmartinez.site
    volumes:
      - ./backend-data:/app/backend/data
      - ./uploads:/app/backend/uploads
